### ISSUE TITLE
Initial Implementation

### ISSUE THREAD

**Issue by KodrAus** [emit-rs/emit_elasticsearch#1]
Closes: https://github.com/emit-rs/emit/issues/11
- [x] Emit events with `_bulk` to Elasticsearch
- [x] Use the `epoch_millis` format for timestamps
- [x] Let users define an index name template like you can in Logstash

**Comment by KodrAus** [comment]
So this isn't actually finished yet :) Will close once I've it all working.

**Comment by nblumhardt** [comment]
Ah sorry, misunderstood your comment :-)

**Comment by KodrAus** [comment]
My fault! At least it's been a good kick to get that last 20% over the line. Just working through some test cases and benches

**Comment by KodrAus** [comment]
Need to get https://github.com/emit-rs/emit/issues/39 sorted so we can implement serialisation properly.
